name: windows_pos_printer
description: Windows POS printer lib
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  printing: ^5.10.4
  universal_io: ^2.2.0
  universal_platform: ^1.0.0+1
  win32: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0
