name: windows_pos_printer
description: Windows POS printer lib
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  printing: ^5.10.1
  universal_io: ^2.0.4
  universal_platform: ^1.0.0+1
  win32: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1